modLoader="javafml"
loaderVersion="[40,)"
issueTrackerURL="https://github.com/petrolpark/pquality/issues"
license="All Rights Reserved"

[[mods]]
modId="pquality"
version="${file.jarVersion}"
displayName="pquality"
#updateJSONURL=""
displayURL="https://www.modrinth.com/mod/pquality"
logoFile="logo.png"
#credits=""
authors="petrolpark"
description='''Items can have qualities that boost their stats'''

[[dependencies.pquality]]
    modId="forge"
    mandatory=true
    versionRange="[43,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.pquality]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="NONE"
    side="BOTH"

[[dependencies.pquality]]
    modId="petrolpark"
    mandatory=true
    versionRange="[1.3.1,)"
    ordering="AFTER"
    side="BOTH"